### ISSUE TITLE
ResLibCal: Convolution fitting of combined models

### ISSUE THREAD

**Issue by tejsner** [McStasMcXtrace/iFit#153]
I am having some issues with convolution fitting of combined models.

I have narrowed down the problem to the evaluation of the model. I have attached a .zip file with everything I try to do. In the first file everything works as intended (single acoustopt model), but in the second file the convolution fitting fails and it seems to be related to the evaluation of the unconvoluted model. I have also found that the fitting works in 1.9 but not 1.10.

If i have a model that is the sum of two 4D models (model = acoustopt1 + acoustopt2), I get the following behaviour:

* I can convolute, and the evaluation onto the data axes work: data(model_conv, params).
* When evaluating the model without convolution I get an error: data(model, params): (Error using iFunc/feval>iFunc_feval_expr (line 346) Failed model evaluation. Saved state in C:)
* This error carries over when performing a fit (convoluted or not).

With a single 4D model (model = acoustopt), everything works as intended apart from fitting in version 1.10.

I am running iFit (1.9/1.10) on MATLAB R2017b on Windows 10.

[convofit_test.zip](https://github.com/McStasMcXtrace/iFit/files/1552684/convofit_test.zip)

**Comment by farhi** [comment]
Many thanks, will commit the fix tomorrow. It is identified, and under control.

**Comment by farhi** [comment]
I think I fixed it. At least your tests seem to go through.

This was a mixed error:

    some statements would fail when using a scalar HKL axis value. It was planned to use grids, vectors, etc, but a special case for scalars is needed
    the axes, which are modified to ease evaluation of a 4D Sqw, need to be restored prior to evaluating the second model term (from your model1+model2 binary operation).

Will now commit the fix.

**Comment by farhi** [comment]
Done with commit https://github.com/McStasMcXtrace/iFit/commit/01b2fb6aaa71d468a36ca2182ed84cbd11597047
