### ISSUE TITLE
cif2hkl: single atom structures yield constant F^2 factors

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/iFit#2]
At least for a couple of examples (attached) cif2hkl generates hkl-lists with constant F^2 for all reflections for neutron radiation. This appears to be the case both for single crystal and powder cases.
Attached is a pair of cif-files with which I experienced the behaviour.
cheers
Erik

[al.cif.txt](https://github.com/McStasMcXtrace/iFit/files/163987/al.cif.txt)
[Fe.cif.txt](https://github.com/McStasMcXtrace/iFit/files/163988/Fe.cif.txt)

**Comment by ebknudsen** [comment]
I forgot to mention: I tried using the web interface as well as the command line utility included in iFit.
The results were identical.

**Comment by farhi** [comment]
Thanks Erik, this is confirmed. Now looking if it comes from cif2hkl or from CrysFML.

**Comment by ebknudsen** [comment]
BTW this does not happen for xrays, nor for electrons - just so you know :-)

**Comment by farhi** [comment]
confirmed that it comes from CrysFML. I upgraded to last svn revision and used WRITE_REFLIST_INFO for a pure export of HKL reflections. Fc is constant. Will inquire with Juan Rodriguez-Carvajal.

**Comment by farhi** [comment]
If the Debye Waller factor is W=0, then exp(-W) is 1. The Al cell has only 1 atom at r=0, so the F2 sum is constant = b_coh. The CIF file should contain a thermal factor to rise a Debye-Waller decrease of F2 as a gaussian profile wrt q.

**Comment by farhi** [comment]
OK, it seems this is a bug, which has been fixed in CrysFML yesterday by Juan. I will upgrade cif2hkl. There was a Biso in the CIF, but was not read properly.

**Comment by farhi** [comment]
Now fixed in iFit with cif2hkl v1.2.
