### ISSUE TITLE
iFit 1.8 seems to have hardcoded PATH to mcstas examples dir ala 2.0

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/iFit#4]
For instance I get:

<pre>
>> mcstas('BNL_H8')
mcstas: Copying instrument /usr/local/lib/mcstas-2.0/examples/BNL_H8.instr in /Users/pkwi/tmp
Error using mcstas (line 231)
Not enough input arguments.
</pre>

**Comment by willend** [comment]
- Perhaps we should do something on the McStas side, e.g. mcstas --libdir giving the relevant PATH to the lib, including env vars etc.

**Comment by willend** [comment]
When the MCSTAS env var is defined prior to opening Matlab/iFit, things work out more or less as expected.

**Comment by farhi** [comment]
Notes about defining MCSTAS and MCXTRACE added in mcstas.m header and Docs/McStas
