### ISSUE TITLE
Plot legends "empty" with ifit-1.8-4 in MATLABR2016b on macOS Sierra

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/iFit#41]
Warning message is:

Warning: Ignoring extra legend entries. 

> In legend>set_children_and_strings (line 658)
>   In legend>make_legend (line 334)
>   In legend (line 282)
>   In factors (line 37) 
- no legends from iData objects plotted

**Comment by farhi** [comment]
Ok, saw that as well, for 1D objects (with errorbars). The new Java objects used since Matlab 2014b+ has messed-up errorbar handling. Will try to find a solution, but this is clearly not a high priority...

**Comment by willend** [comment]
Fair enough. :-) 

I guess one could in principle do a hack here: A new function that adds a "text" pr axis child with a character / symbol and color? Will see if I can write that up - will then be contributed here.

**Comment by farhi** [comment]
With current branch, using:

- plot(object, 'legend')

will properly display the legend...
So I consider this solved ("oki doki ?").

**Comment by willend** [comment]
Jup! 

![like](https://cloud.githubusercontent.com/assets/8593355/19190143/13914406-8c9c-11e6-8e2a-9eddad9469a5.png)

**Comment by willend** [comment]
Hi there,

With the latest beta the behaviour is (of course) the same... But I saw another issue: When multiple plot(object,'legend') are used, only the last one is shown. The same problem if plot([a b],'legend') is used.

P

**Comment by farhi** [comment]
On the way to be solved with commi https://github.com/McStasMcXtrace/iFit/commit/bab7cecaa0983834b63da3adebb83f59d9f102a2

Must test with Matlab 2014b+ for HG2.

Should store the handles in the UserData contextual menu, and add an 'Toggle legend...' item to show/hide it.

**Comment by farhi** [comment]
Fixed by adding a 'Show legend' item in the axis contextual menu. This can be used when the standard Matlab 'legend' icon/menu fails. Commit https://github.com/McStasMcXtrace/iFit/commit/259e0d0a1db22f9b1c082a9c05c39d9edbe782f2

**Comment by willend** [comment]
@farhi is there an easy way to call the 'Show legend' callback from a script?

**Comment by farhi** [comment]
Hi Peter,

you can try:

- plot(iData_objects, ..., 'legend')
