### ISSUE TITLE
Hidden dependency for libxp6 on Ubuntu 16.04

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/iFit#42]
Hi there,

I just upgraded a virtual Ubuntu machine with the stock iFit form mccode.org to 16.04. On starting iFit, Matlab vomits:

<pre>
mcstas@mcstas-virtual-machine:~$ ifit 
Starting iFit using /opt/MATLAB/MATLAB_Compiler_Runtime/v713
My Own Exception: Fatal error loading library /opt/MATLAB/MATLAB_Compiler_Runtime/v713/...
bin/glnxa64/libmwmclmcr.so ...
Error: libXp.so.6: cannot open shared object file: No such file or directory
</pre>

Unfortunately it seems Ubuntu is not shipping the relevant library for recent Ubuntu versions, but the one from 12.04 seems to work, e.g. from http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxp/libxp6_1.0.2-1ubuntu1_amd64.deb .

I can add it to the mccode repo if you want?
Best,
Peter

**Comment by willend** [comment]
(I guess the Matlab compiler runtime package should still raise a dependency for libxp6)

**Comment by farhi** [comment]
Hy Peter, 

true, libxp6 is not part of Ubuntu 16.04. A temporary solution is indeed to add the libxp6 http://packages.ubuntu.com/trusty/libxp6 to our packages.mccode.org
I will check if the recent Matlab compiler versions (R2016b) still relies on libxp6.

The dependency by itself has been addressed and added to the 'standalone' generation script in commit https://github.com/McStasMcXtrace/iFit/commit/36f914cc2df82a7bd41144aaa0c2eed83d0a12e3#diff-25b09a8e0c6008afbe6cabdb44bee5fd

Cheers, E.

**Comment by farhi** [comment]
libxp6 deb now in packages.mccode.org repo.
This solves the issue (for the near future at least).
