### ISSUE TITLE
cif2hkl issue: Problems compiling using gfortran on Mac

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/iFit#48]
Hi E,

Just tried compiling both the version available at the barns website plus the code in the iFit git, I get:

<pre>
pkwi@pkwi-mbp2016:~/tmp/cif2hkl$ gfortran -c cif2hkl.F90 
cif2hkl.F90:24187:132:

                                 if(txyz(1) == lat_trans(1,l) .and. txyz(2) == lat_trans(2,l) .and. txyz(3) == lat_trans(3,l)) cycle p2
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
cif2hkl.F90:24234:132:

                                 if(txyz(1) == lat_trans(1,l) .and. txyz(2) == lat_trans(2,l) .and. txyz(3) == lat_trans(3,l)) cycle p2
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
cif2hkl.F90:33209:8:

     Use CFML_Crystallographic_Symmetry, only: Sym_Oper_Type, Space_Group_Type, Lattice_Centring_Type, &
        1
<b>Fatal Error: Can't open module file 'cfml_crystallographic_symmetry.mod' for reading at (1): No such file or directory</b>
f951: some warnings being treated as errors
compilation terminated.
</pre>

Could cfml_crystallographic_symmetry.mod be missing from the .F90 file?

Peter

**Comment by farhi** [comment]
Seems this is not the case on Linux.

How about using the cif2hkl_maci64 executable from https://github.com/McStasMcXtrace/iFit/blob/master/Scripts/Models/Factory/cif2hkl_maci64 ?

**Comment by willend** [comment]
OK - but that one is for execution from within Matlab I guess?

What I was trying was to get a stand-alone binary of cif2hkl (eventually shipping that for the different platforms with McStas maybe)

**Comment by farhi** [comment]
Seems the cif2hkl_maci64 is not linked to Matlab libraries. So it works on my MacBook and virtual machines as a 'normal' executable, which can be included in a 3rd party package. Try it, and if it works we can close the issue. Please include the source code as well.

**Comment by willend** [comment]
This indeed seems to be the case! 

Do you remember anything about where / when that binary was built? (We can surely use the binary as is, but it would be good to know how to build it in the future.)

Wrt. source code - sure, will include that as well. My suggestion is that I make an "independent" tools package for cif2hkl? I.e. own directory and CMakefiles.txt etc. in the McCode source tree.

**Comment by farhi** [comment]
Compilation with

- gfortran -O -o cif2hkl_maci64 cif2hkl.F90 -lm

works OK under Mavericks with HPC gfortran. May also compile it with --static flag.

**Comment by willend** [comment]
OK. Fails on macOS Sierra with HPC gfortran 6.2 - same issue with gfortran/gcc from homebrew. Any idea what version # your gfortran was?

**Comment by willend** [comment]
OK, tried downgrading myself - for gfortran 4.9 it seems to compile OK. Will see how it behaves with a newer gfortran on Linux also.

**Comment by willend** [comment]
Played a bit with compiler options, seems gfortran 5 and 6 are simply slightly more strict... It works if one uses

gfortran -O -o cif2hkl_maci64 cif2hkl.F90 -lm -ffree-line-length-0
