### ISSUE TITLE
Packaging: hdf5storage debian

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/iFit#80]

**Comment by farhi** [comment]
exists as:

- https://packages.ubuntu.com/xenial/python-hdf5storage

**Comment by farhi** [comment]
should put that one in packages.mccode.org to avoid searching...

**Comment by willend** [comment]
Maybe we should consider a more "fine-grained" set of repositories? I.e. one pr Debian plus one pr Ubuntu "named" release. My plan is still that (at least McStas/McXtrace) will eventually get hosted from ESS DMSC, so we'd better have all of that in mind...

**Comment by farhi** [comment]
True. Tha 'all' packages such as hdf5storage are Debian, but can be used in Xenial and Trusty as well. I have not tested all my packages under Debian, but this is indeed a good thing to try out. The main difference between distribution for our distro-specific binaries rely currently on openmpi:

- Ubuntu Trusty 14.04 and Debian Jesie: 1.6.5
- Ubuntu Xenial 16.04: 1.10
- Ubuntu Zesty 17.04 and Debian Strech and Sid: 2.0

It's surely a mess with all these openmpi changes...

**Comment by farhi** [comment]
I pushed the python-hdf5storage package from xenial into our packages.mccode.org 'all' branch. Has loose package dependency without specific release requirements for numpy and h5py.

This package exists in Ubuntu Xenial, and Debian Stretch/Sid. Does not exist in current Jessie (Debian 8).

**Comment by willend** [comment]
I think this is not a good solution. When an official package and official channel exists, we should default to use that. I.e. only "our own stuff" should  be in the 'all' branch

**Comment by farhi** [comment]
Ok, then move it to the Trusty branch only ? But Debian Jessie does not distribute it either...

**Comment by willend** [comment]
Move to Trusty with copy in Jessie... :-) In other words:  

We should not risk taking preference over an official package - i.e. OK to copy everywhere but Xenial

**Comment by farhi** [comment]
OK, just done so. Now only in Trusty 'all'. The Jessie branch will have to be created in order to solve potential broken dependency with Jessie. 

But Jessie is very similar to Trusty (has same openmpi version), so I guess Jessie could use the same repo as our Trusty specific one. 

Next coming Strech, and Sid will not have this issue (but others as openmpi is there 2.0 ...).
