### ISSUE TITLE
Question: Does the standalone iFit not support PyFit?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/iFit#83]
Hi @farhi,

@climbcat and I are starting to experiment with iFit (for the purpose of web-based data analysis for e-neutrons.org).

We thought that PyFit looks really promising, but we can't seem to make it work with a standalone (compiled) iFit.

On Ubuntu 16.04 with latest iFit we get

<pre>
mcstas@mcstas-virtual-machine:~/iFit/Applications/Python$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mlabwrap import mlab
Matlab path    /usr/local/bin/matlab

Could not open matlab, is it in guess?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mlabwrap.py", line 688, in <module>
    mlab = MlabWrap()
  File "mlabwrap.py", line 425, in __init__
    self._eval('isd=double(isdeployed);')
  File "mlabwrap.py", line 600, in _eval
    on_new_output=on_new_output)
  File "matlabpipe.py", line 206, in eval
    ret = self._sync_output(on_new_output)
  File "matlabpipe.py", line 417, in _sync_output
    ret = self._read_until(self.expected_output_end, on_new_output)
  File "matlabpipe.py", line 401, in _read_until
    raise MatlabConnectionError('timeout')
matlabpipe.MatlabConnectionError: timeout
>>> 
</pre>
(even though it says "matlab" above, that is a link to ifit...)

The iFit source code is from current main on GitHub - compatibility issue?

**Comment by farhi** [comment]
Absolutely. This PyFit was done to work initially with a real Matlab. I've not yet adapted it to work with the standalone. Now adding as an enhancement and bug.

**Comment by farhi** [comment]
I'm afraid it will be complicated this way. There may be other ways to communicate...

**Comment by farhi** [comment]
Just found a new py-mat interface using 0MQ:

- https://github.com/bastibe/transplant

it is much simpler than previous implementations. Works OK with Matlab, will test with iFit compiled.
It probably requires to embed in the iFit executable the .m functions in:

- https://github.com/bastibe/transplant/tree/master/transplant

this looks very promissing.

**Comment by farhi** [comment]
Other implementation with 0MQ, more complex:

- https://arokem.github.io/python-matlab-bridge/

**Comment by farhi** [comment]
The 0MQ solutions above require python3.

**Comment by farhi** [comment]
The initial mlabwrap is still the best as it does not depend on external libraries (no 0MQ or matlab engine), using a Popen. As of today, the Pipe can be opened with standalone ifit, but commands are not executed properly. However there is a clear improvement !!

With the current modifications, it may be desirable to first define path to ifit/matlab executable:

- MLABRAW_CMD_STR=ifit

else will try to find a pure Matlab.

**Comment by farhi** [comment]
Solving this would allow to use e.g. iPython notebook/Jupyter, which also solves the issue with Int'l accent chars (crash of standalone termnal).

**Comment by farhi** [comment]
Done with commit https://github.com/McStasMcXtrace/iFit/commit/8eb96e7aeed7e41c16c2afd53033132576cb5364

**Comment by farhi** [comment]
The timeout issue with Py3 can be partly solved changing the timeout in 

- Matlab.waitidle() 

and using

- Matlab.eval(cmd, ,waitidle=False)

**Comment by farhi** [comment]
Now supports both Python2 and 3. Most flush stall are solved.
Use IPython notebook as default 'pyfit' command. very nice looking. see https://github.com/McStasMcXtrace/iFit/commit/a100715bf87f55ad6f773dfd6d28207ae4b33ecd
